---
title: "1: Geospatial Analytics for Public Good"
author: "Magdalene Chan"
date: 2023-11-25
date-modified: "last-modified"
execute: 
  warning: false
editor: 
  markdown: 
    wrap: 72
---

# Objectives

As city-wide urban infrastructures become increasingly digital, datasets
from technologies like GPS and RFID on vehicles offer opportunities to
track movement patterns over space and time. For instance, smart cards
and GPS devices on public buses collect routes and ridership data,
containing valuable structure and patterns for understanding human
movement and behavior within cities. Yet, despite their potential, the
practical use of these extensive location-aware datasets often remains
limited to basic tracking and mapping within GIS applications due to the
lack of comprehensive spatial and spatio-temporal analysis functions in
conventional GIS tools.

Exploratory Spatial Data Analysis (ESDA) holds tremendous potential to
address such complex problems. In this study, appropriate Local
Indicators of Spatial Association (GLISA) and Emerging Hot Spot Analysis
(EHSA) will be applied to undercover the spatial and spatio-temporal
mobility patterns of public bus passengers in Singapore.

# Tasks

The following tasks will be addressed in this exercise:

## Geovisualisation and Analysis

1.  Compute the passenger trips generated by origin at the hexagon level
    for the following time periods:
    1.  Weekday morning peak (6am to 9am)
    2.  Weekday afternoon peak (5pm to 8pm)
    3.  Weekend/holiday morning peak (11am to 2pm)
    4.  Weekend/holiday evening peak (4pm to 7pm)
2.  Display the geographical distribution of the passenger trips by
    using appropriate geovisualisation methods.
3.  Describe the spatial patterns revealed by the geovisualisation (not
    more than 200 words per visual).

Local Indicators of Spatial Association (LISA) Analysis

1.  Compute LISA of the passengers trips generate by origin at hexagon
    level. Display the LISA maps of the passengers trips generate by
    origin at hexagon level. The maps should only display the
    significant (i.e. p-value \< 0.05) With reference to the analysis
    results, draw statistical conclusions (not more than 200 words per
    visual). Emerging Hot Spot Analysis(EHSA) With reference to the
    passenger trips by origin at the hexagon level for the four time
    intervals given above:

Perform Mann-Kendall Test by using the spatio-temporal local Gi\*
values, Prepared EHSA maps of the Gi\* values of the passenger trips by
origin at the hexagon level. The maps should only display the
significant (i.e. p-value \< 0.05). With reference to the EHSA maps and
data visualisation prepared, describe the spatial patterns reveled. (not
more than 250 words per cluster).
