project:
  type: website

website:
  title: "Geospatial Analytics"
  image: Images/logo.png
  favicon: Images/favicon_small.png
  open-graph: true
  site-url: https://geospatial2023.netlify.app/
  repo-url: https://github.com/magdalenecjw/ISSS624-Geospatial
  navbar:
    background: "#f0eeeb"
    logo: Images/logo.png
    logo-alt: "Geospatial Analytics"
    title: false
    collapse-below: lg
    right:
      - text: "In-class Exercise"
        menu: 
        - text: "Lesson 1"
          href: In_Class_Exercise/Lesson1.qmd
      - text: "Hands-on Exercise"
        menu: 
        - text: "1a: Geospatial Data Wrangling"
          href: Hands_on_Exercise/Ex1/Hands_on_Ex1a.qmd
        - text: "1b: Choropleth Mapping"
          href: Hands_on_Exercise/Ex1/Hands_on_Ex1b.qmd
        - text: "2a: Spatial Weights and Applications"
          href: Hands_on_Exercise/Ex2/Hands_on_Ex2a.qmd
        - text: "2b: Global Measures of Spatial Autocorrelation"
          href: Hands_on_Exercise/Ex2/Hands_on_Ex2b.qmd
        - text: "2c: Local Measures of Spatial Autocorrelation"
          href: Hands_on_Exercise/Ex2/Hands_on_Ex2c.qmd
      - text: "Take Home Exercise"
        menu: 
        - text: "Exercise 1"
          href: Take_Home_Exercise/Ex1/Take_home_Ex1.qmd
        - text: "Exercise 2"
          href: Take_Home_Exercise/Ex2/Take_home_Ex2.qmd

  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    background: "#000000"
    center:  
      - href: https://geospatial2023.netlify.app/
        icon: house-fill
        aria-label: Home
      - href: https://github.com/magdalenecjw/ISSS624-Geospatial
        icon: github
        aria-label: GitHub
      - href: https://public.tableau.com/app/profile/magdalene.chan
        icon: bar-chart-fill
        aria-label: Tableau
      - href: https://www.linkedin.com/in/chanmagdalene/
        icon: linkedin
        aria-label: LinkedIn
      - href: mailto:jwchan.2021@mitb.smu.edu.sg
        icon: envelope-fill
        aria-label: Email

format:
  html:
    theme: [lux, styles.scss]
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto