{
  "hash": "79362b2a1e3886bb2cb17e488d937f7e",
  "result": {
    "markdown": "---\ntitle: \"5: Spatial Econometric Interaction Model\"\nauthor: \"Magdalene Chan\"\ndate: 2023-12-16\ndate-modified: \"last-modified\"\nexecute: \n  warning: false\n---\n\n\n## Getting started\n\nThe key packages to be used in this exercise are:\n\n-   **tmap**: for thematic mapping\n-   **sf**: for geospatial data wrangling\n-   **spdep**: for spatial weights matrix \n-   **spflow**: for spatial econometric models of O-D flow\n-   **tidyverse**: for non-spatial data wrangling\n\nHowever, as the latest version of the **spflow** package is not available on CRAN yet, the `install_github()` function of **devtools** package will be used to install the **spflow** package first. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevtools::install_github(\"LukeCe/spflow\")\n# Check that version number should be at least 0.1.0.9010\n```\n:::\n\n\nThe code chunk below then uses `p_load()` of **pacman** package to check if the required packages have been installed on the computer. If they are, the packages will be launched. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tmap, sf, spdep, sp, Matrix, spflow, knitr, tidyverse)\n```\n:::\n\n\n## Data Preparation\n\nBefore calibrating Spatial Econometric Interaction Models using **spflow**, three data sets are required:\n\n-   spatial weights\n-   tibble data frame O-D flow matrix (with distance)\n-   tibble data frame consisting of explanatory variables (does not need to differentiate origin vs. destination variables)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_nb <- read_rds(\"data/rds/mpsz_nb.rds\")\nmpsz_flow <- read_rds(\"data/rds/mpsz_flow.rds\")\nmpsz_var <- read_rds(\"data/rds/mpsz_var.rds\")\n```\n:::\n\n\n## Creating `spflow_network-class` objects\n\n`spflow_network-class` is an S4 class containing information on a spatial network which is composed by a set of nodes that are linked by some neighbourhood relation. It can be created using `spflow_network()` function of **spflow** package. For our model, we choose the contiguity based neighbourhood structure. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_net <- spflow_network(\n  id_net = \"sg\",  # assign an id name, can give it any input\n  node_neighborhood = nb2mat(mpsz_nb$by_contiguity),\n  node_data = mpsz_var,\n  node_key_column = \"SZ_CODE\"\n)\n\nmpsz_net\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSpatial network nodes with id: sg\n--------------------------------------------------\nNumber of nodes: 313\nAverage number of links per node: 6.077\nDensity of the neighborhood matrix: 1.94% (non-zero connections)\n\nData on nodes:\n                SZ_NAME SZ_CODE BUSSTOP_COUNT AGE7_12 AGE13_24 AGE25_64\n1      INSTITUTION HILL  RVSZ05             2     330      360     2260\n2        ROBERTSON QUAY  SRSZ01            10     320      350     2200\n3          FORT CANNING  MUSZ02             6       0       10       30\n4      MARINA EAST (MP)  MPSZ05             2       0        0        0\n5               SENTOSA  SISZ01             1     200      260     1440\n6        CITY TERMINALS  BMSZ17            10       0        0        0\n---                 ---     ---           ---     ---      ---      ---\n308            NEE SOON  YSSZ07            12      90      140      590\n309       UPPER THOMSON  BSSZ01            47    1590     3660    15980\n310          SHANGRI-LA  AMSZ05            12     810     1920     9650\n311          TOWNSVILLE  AMSZ04             9     980     2000    11320\n312           MARYMOUNT  BSSZ02            25    1610     4060    16860\n313 TUAS VIEW EXTENSION  TSSZ06            11       0        0        0\n    SCHOOL_COUNT BUSINESS_COUNT RETAILS_COUNT FINSERV_COUNT ENTERTN_COUNT\n1              1              6            26             3             0\n2              0              4           207            18             6\n3              0              7            17             0             3\n4              0              0             0             0             0\n5              0              1            84            29             2\n6              0             11            14             4             0\n---          ---            ---           ---           ---           ---\n308            0              0             7             0             0\n309            3             21           305            30             0\n310            3              0            53             9             0\n311            1              0            83            11             0\n312            3             19           135             8             0\n313            0             53             3             1             0\n    FB_COUNT LR_COUNT COORD_X COORD_Y\n1          4        3  103.84    1.29\n2         38       11  103.84    1.29\n3          4        7  103.85    1.29\n4          0        0  103.88    1.29\n5         38       20  103.83    1.25\n6         15        0  103.85    1.26\n---      ---      ---     ---     ---\n308        0        0  103.81     1.4\n309        5       11  103.83    1.36\n310        0        0  103.84    1.37\n311        1        1  103.85    1.36\n312        3       11  103.84    1.35\n313        0        0  103.61    1.26\n```\n:::\n:::\n\n\n`spflow_network_pair-class` is an S4 class containing information on O-D pairs. It can be created using `spflow_network_pair()` function of **spflow** package. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_net_pairs <- spflow_network_pair(\n  id_orig_net = \"sg\",\n  id_dest_net = \"sg\",\n  pair_data = mpsz_flow,\n  orig_key_column = \"ORIGIN_SZ\",\n  dest_key_column = \"DESTIN_SZ\"\n)\n\nmpsz_net_pairs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSpatial network pair with id: sg_sg\n--------------------------------------------------\nOrigin network id: sg (with 313 nodes)\nDestination network id: sg (with 313 nodes)\nNumber of pairs: 97969\nCompleteness of pairs: 100.00% (97969/97969)\n\nData on node-pairs:\n      DESTIN_SZ ORIGIN_SZ DISTANCE TRIPS\n1        RVSZ05    RVSZ05        0    67\n314      SRSZ01    RVSZ05   305.74   251\n627      MUSZ02    RVSZ05   951.83     0\n940      MPSZ05    RVSZ05  5254.07     0\n1253     SISZ01    RVSZ05     4975     0\n1566     BMSZ17    RVSZ05  3176.16     0\n---         ---       ---      ---   ---\n96404    YSSZ07    TSSZ06 26972.97     0\n96717    BSSZ01    TSSZ06 25582.48     0\n97030    AMSZ05    TSSZ06 26714.79     0\n97343    AMSZ04    TSSZ06 27572.74     0\n97656    BSSZ02    TSSZ06  26681.7     0\n97969    TSSZ06    TSSZ06        0   270\n```\n:::\n:::\n\n\n`spflow_network_multi-class` is an S4 class containing information on the origins, the destinations, and the O-D pairs. It can be created using `spflow_network_multi()` function of **spflow** package and only works on `spflow_network-class` and `spflow_network_pair-class`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_multi_net <- spflow_network_multi(mpsz_net,\n                                       mpsz_net_pairs)\n\nmpsz_multi_net\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCollection of spatial network nodes and pairs\n--------------------------------------------------\nContains 1 spatial network nodes  \n    With id :  sg\nContains 1 spatial network pairs  \n    With id :  sg_sg\n\nAvailability of origin-destination pair information:\n\n ID_ORIG_NET ID_DEST_NET ID_NET_PAIR COMPLETENESS     C_PAIRS  C_ORIG  C_DEST\n          sg          sg       sg_sg      100.00% 97969/97969 313/313 313/313\n```\n:::\n:::\n\n\n## Check for Multicollinearity \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_formula <- log(1 + TRIPS) ~\n  BUSSTOP_COUNT + \n  AGE7_12 + \n  AGE13_24 + \n  AGE25_64 + \n  SCHOOL_COUNT + \n  BUSINESS_COUNT + \n  RETAILS_COUNT + \n  FINSERV_COUNT + \n  P_(log(DISTANCE + 1))   # P stands for the impedence\n\ncor_mat <- pair_cor(\n  mpsz_multi_net,\n  spflow_formula = cor_formula,\n  add_lags_x = FALSE\n)\n\n# Labels\ncolnames(cor_mat) <- paste0(substr(colnames(cor_mat),1,3),\"...\")\n\ncor_image(cor_mat)\n```\n\n::: {.cell-output-display}\n![](In_Class_Ex5_files/figure-html/unnamed-chunk-7-1.png){width=1152}\n:::\n:::\n\n\n## Base Model Calibration\n\nThere are currently three estimators of spatial econometric interaction models  supported by **spflow** package: \n\n-   Maximum likelihood estimation (MLE) -- default estimation procedure.\n-   Spatial two-stage least squares (S2SLS) -- activate the S2SLS estimation via the `estimation_control` argument using the input `spflow_control(estimation_method = \"s2sls\")`.\n-   Bayesian Markov Chain Monte Carlo (MCMC) -- activate the MCMC estimation via the `estimation_control` argument using the input `spflow_control(estimation_method = \"mcmc\")`.\n\nThe function offers a formula interface adapted to spatial interaction models, which has the following structure: \n\n> Y ~ O_(X1) + D_(X2) + I_(X3) + P_(X4)\n\n-   O_(...) and D_(...) indicate which variables are used as characteristics of the origins and destinations respectively\n-   I_(...) indicates variables that should be used for the intra-regional parameters\n-   P_(...) declares which variables describe origin-destination pairs, which usually will include a measure of distance (distance decay).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase_model <- spflow(\n  spflow_formula = log(1 + TRIPS) ~\n    O_(BUSSTOP_COUNT + \n         AGE25_64) + \n    D_(SCHOOL_COUNT + \n         BUSINESS_COUNT + \n         RETAILS_COUNT + \n         FINSERV_COUNT) + \n    P_(log(DISTANCE + 1)),\n  spflow_networks = mpsz_multi_net\n)\n\nbase_model\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n--------------------------------------------------\nSpatial interaction model estimated by: MLE  \nSpatial correlation structure: SDM (model_9)\nDependent variable: log(1 + TRIPS)\n\n--------------------------------------------------\nCoefficients:\n                          est     sd   t.stat  p.val\nrho_d                   0.680  0.004  192.554  0.000\nrho_o                   0.678  0.004  187.732  0.000\nrho_w                  -0.396  0.006  -65.591  0.000\n(Intercept)             0.410  0.065    6.266  0.000\n(Intra)                 1.313  0.081   16.263  0.000\nD_SCHOOL_COUNT          0.017  0.002    7.885  0.000\nD_SCHOOL_COUNT.lag1     0.002  0.004    0.551  0.581\nD_BUSINESS_COUNT        0.000  0.000    3.015  0.003\nD_BUSINESS_COUNT.lag1   0.000  0.000   -0.249  0.804\nD_RETAILS_COUNT         0.000  0.000   -0.306  0.759\nD_RETAILS_COUNT.lag1    0.000  0.000    0.152  0.880\nD_FINSERV_COUNT         0.002  0.000    6.787  0.000\nD_FINSERV_COUNT.lag1   -0.002  0.001   -3.767  0.000\nO_BUSSTOP_COUNT         0.002  0.000    6.806  0.000\nO_BUSSTOP_COUNT.lag1   -0.001  0.000   -2.364  0.018\nO_AGE25_64              0.000  0.000    7.336  0.000\nO_AGE25_64.lag1         0.000  0.000   -2.797  0.005\nP_log(DISTANCE + 1)    -0.050  0.007   -6.793  0.000\n\n--------------------------------------------------\nR2_corr: 0.6942944  \nObservations: 97969  \nModel coherence: Validated\n```\n:::\n:::\n\n\n:::callout-note\n### Insights and Interpretation of results\n\nBased on the print result above, model 9 and MLE estimator is used (defaults). The R^2^ value is 0.694, which means the model accounts for 69.42% of the variation of flows.\n\nrho_d - destination constrain\nrho_o - origin constrain\nrho_w - intrazonal constrain\n\n`D_SCHOOL_COUNT` has a t.stat that is statistically significant, but the t.stat of its lag is not statistically significant. Similarly for `D_BUSINESS_COUNT` and its lag. \n\n- School and Business counts in the zone will affect the attractiveness, but not school and business counts in neighbouring zones.\n\n`D_RETAILS_COUNT` and its lag are both not statistically significant.\n\n- Not a good explanatory variable for weekday morning peak. \n\n`D_FINSERV_COUNT` and its lag are both statistically significant. \n\n- Good explanatory variable: Financial services counts in the zone and in neighbouring zones will affect the attractiveness\n\n`O_BUSSTOP_COUNT`\tand its lag are both statistically significant. Simialrly for `O_AGE25_64` and and its lag. \n\n- Good explanatory variable: Financial services counts in the zone and in neighbouring zones will affect the attractiveness\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nold_par <- par(mfrow = c(1,3),\n               mar = c(2,2,2,2))\nspflow_moran_plots(base_model)\n```\n\n::: {.cell-output-display}\n![](In_Class_Ex5_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(old_par)\n```\n:::\n\n\nNext, `pair_cor()` can be used to inspect the relationship of the residual and the explanatory variables by using the code chunk below. \n\n> Check for multi-collinearity again. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorr_residual <- pair_cor(base_model)\ncolnames(corr_residual) <- substr(colnames(corr_residual),1,3)\ncor_image(corr_residual)\n```\n\n::: {.cell-output-display}\n![](In_Class_Ex5_files/figure-html/unnamed-chunk-10-1.png){width=1152}\n:::\n:::\n\n\n## Working with model control\n\nExample of running MLE Model 8:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspflow_formula <- log(1 + TRIPS) ~\n    O_(BUSSTOP_COUNT + \n         AGE25_64) + \n    D_(SCHOOL_COUNT + \n         BUSINESS_COUNT + \n         RETAILS_COUNT + \n         FINSERV_COUNT) + \n    P_(log(DISTANCE + 1))\n\nmodel_control <- spflow_control(\n  estimation_method = \"mle\",\n  model = \"model_8\"\n)\n\nmle_model8 <- spflow(\n  spflow_formula,\n  spflow_networks = mpsz_multi_net,\n  estimation_control = model_control\n)\n\nmle_model8\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n--------------------------------------------------\nSpatial interaction model estimated by: MLE  \nSpatial correlation structure: SDM (model_8)\nDependent variable: log(1 + TRIPS)\n\n--------------------------------------------------\nCoefficients:\n                          est     sd    t.stat  p.val\nrho_d                   0.689  0.003   196.832  0.000\nrho_o                   0.687  0.004   192.214  0.000\nrho_w                  -0.473  0.003  -142.469  0.000\n(Intercept)             1.086  0.049    22.275  0.000\n(Intra)                 0.840  0.075    11.255  0.000\nD_SCHOOL_COUNT          0.019  0.002     8.896  0.000\nD_SCHOOL_COUNT.lag1     0.019  0.004     5.130  0.000\nD_BUSINESS_COUNT        0.000  0.000     3.328  0.001\nD_BUSINESS_COUNT.lag1   0.000  0.000     1.664  0.096\nD_RETAILS_COUNT         0.000  0.000    -0.414  0.679\nD_RETAILS_COUNT.lag1    0.000  0.000    -0.171  0.864\nD_FINSERV_COUNT         0.002  0.000     6.150  0.000\nD_FINSERV_COUNT.lag1   -0.003  0.001    -4.601  0.000\nO_BUSSTOP_COUNT         0.003  0.000     7.676  0.000\nO_BUSSTOP_COUNT.lag1    0.000  0.000     0.552  0.581\nO_AGE25_64              0.000  0.000     6.870  0.000\nO_AGE25_64.lag1         0.000  0.000    -0.462  0.644\nP_log(DISTANCE + 1)    -0.125  0.005   -22.865  0.000\n\n--------------------------------------------------\nR2_corr: 0.6965974  \nObservations: 97969  \nModel coherence: Validated\n```\n:::\n:::\n\n\n> The R^2^ of Model 8 is 0.696, meaning the model accounts for 69.65% of the variation of flows -- slightly higher than that for Model 9. \n\nExample of running MLE Model 1 (unconstrained):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_control <- spflow_control(\n  estimation_method = \"mle\",\n  model = \"model_1\"\n)\n\nmle_model1 <- spflow(\n  spflow_formula,\n  spflow_networks = mpsz_multi_net,\n  estimation_control = model_control\n)\n\nmle_model1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n--------------------------------------------------\nSpatial interaction model estimated by: OLS  \nSpatial correlation structure: SLX (model_1)\nDependent variable: log(1 + TRIPS)\n\n--------------------------------------------------\nCoefficients:\n                          est     sd    t.stat  p.val\n(Intercept)            11.384  0.069   164.255  0.000\n(Intra)                -6.006  0.112   -53.393  0.000\nD_SCHOOL_COUNT          0.093  0.003    28.599  0.000\nD_SCHOOL_COUNT.lag1     0.255  0.006    44.905  0.000\nD_BUSINESS_COUNT        0.001  0.000    10.036  0.000\nD_BUSINESS_COUNT.lag1   0.003  0.000    18.274  0.000\nD_RETAILS_COUNT         0.000  0.000    -1.940  0.052\nD_RETAILS_COUNT.lag1    0.000  0.000    -2.581  0.010\nD_FINSERV_COUNT         0.005  0.000    10.979  0.000\nD_FINSERV_COUNT.lag1   -0.016  0.001   -17.134  0.000\nO_BUSSTOP_COUNT         0.014  0.001    25.865  0.000\nO_BUSSTOP_COUNT.lag1    0.015  0.001    21.728  0.000\nO_AGE25_64              0.000  0.000    14.479  0.000\nO_AGE25_64.lag1         0.000  0.000    14.452  0.000\nP_log(DISTANCE + 1)    -1.281  0.008  -165.327  0.000\n\n--------------------------------------------------\nR2_corr: 0.2831458  \nObservations: 97969  \nModel coherence: Validated\n```\n:::\n:::\n\n\n> The R^2^ of Model 1 (unconstrained) is only 0.2831, meaning the model accounts for 28.31% of the variation of flows.\n\nExample of running MLE Model 2 (constrained):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_control <- spflow_control(\n  estimation_method = \"mle\",\n  model = \"model_2\"\n)\n\nmle_model2 <- spflow(\n  spflow_formula,\n  spflow_networks = mpsz_multi_net,\n  estimation_control = model_control\n)\n\nmle_model2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n--------------------------------------------------\nSpatial interaction model estimated by: MLE  \nSpatial correlation structure: SDM (model_2)\nDependent variable: log(1 + TRIPS)\n\n--------------------------------------------------\nCoefficients:\n                          est     sd   t.stat  p.val\nrho_d                   0.731  0.003  218.603  0.000\n(Intercept)             3.068  0.067   45.899  0.000\n(Intra)                -0.398  0.093   -4.291  0.000\nD_SCHOOL_COUNT          0.063  0.003   24.291  0.000\nD_SCHOOL_COUNT.lag1     0.054  0.005   11.802  0.000\nD_BUSINESS_COUNT        0.001  0.000    8.790  0.000\nD_BUSINESS_COUNT.lag1   0.001  0.000    3.925  0.000\nD_RETAILS_COUNT         0.000  0.000   -1.076  0.282\nD_RETAILS_COUNT.lag1    0.000  0.000    0.251  0.802\nD_FINSERV_COUNT         0.007  0.000   18.054  0.000\nD_FINSERV_COUNT.lag1   -0.009  0.001  -12.691  0.000\nO_BUSSTOP_COUNT         0.003  0.000    8.269  0.000\nO_BUSSTOP_COUNT.lag1    0.004  0.001    7.808  0.000\nO_AGE25_64              0.000  0.000    3.918  0.000\nO_AGE25_64.lag1         0.000  0.000    4.421  0.000\nP_log(DISTANCE + 1)    -0.351  0.007  -47.000  0.000\n\n--------------------------------------------------\nR2_corr: 0.5527887  \nObservations: 97969  \nModel coherence: Validated\n```\n:::\n:::\n\n\n> The R^2^ of Model 2 (constrained) is 0.5527, meaning the model accounts for 55.27% of the variation of flows -- higher than that of Model 1 (unconstrained).\n\n",
    "supporting": [
      "In_Class_Ex5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}